name: burkaz
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/dahiAbi/burkaz

environment:
  sdk: ^3.10.0-290.1.beta

# Add regular dependencies here.
dependencies:
  binarize: ^2.0.0
  ffi: ^2.1.4
  hooks: ^0.20.4
  meta: ^1.17.0
  native_toolchain_rs: ^0.1.2+3
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
